version: '3.5'

services:
  postgres:
    image: postgres
    expose:
      - "5433"
    ports:
      - "5433:5433"
    restart: always
    command: -p 5433
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: credit-control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lebara@QAZ@
  
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/var/lib/creditControl/redis/data

  api:
    build: ./credit_control_backend
    volumes:
      - ./credit_control_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./credit_control_backend/.env

  api_nginx:
    image: nginx:1.19.0
    ports:
      - "3000:3000"
    volumes:
      - ./credit_control_backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/testcredit.lebara.sa/star-lebara-sa.crt:/etc/ssl/testcredit.lebara.sa/star-lebara-sa.crt
      - /etc/ssl/testcredit.lebara.sa/star-lebara-sa.key:/etc/ssl/testcredit.lebara.sa/star-lebara-sa.key
    depends_on:
      - api

  celery_worker:
    build: ./credit_control_backend
    command: /app/docker_scripts/start-celeryworker.sh
    volumes:
      - ./credit_control_backend:/app
    env_file:
      - ./credit_control_backend/.env
    depends_on:
      - postgres
      - redis

  celery_beat:
    build: ./credit_control_backend
    command: /app/docker_scripts/start-celerybeat.sh
    volumes:
      - ./credit_control_backend:/app
    env_file:
      - ./credit_control_backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./credit_control_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/testcredit.lebara.sa/star-lebara-sa.crt:/etc/ssl/testcredit.lebara.sa/star-lebara-sa.crt
      - /etc/ssl/testcredit.lebara.sa/star-lebara-sa.key:/etc/ssl/testcredit.lebara.sa/star-lebara-sa.key
    depends_on:
      - api
    env_file:
      - ./credit_control_frontend/.env

volumes:
  postgresdata: { }
  cache: { }
